linker flag for libprocps:
apparently even though "-lX" are called linker flags these should not be assigned to LINK_FLAGS (as before)
instead listed (at the appropriate position, e.g. end) in TARGET_LINK_LIBRARIES without "-l", see:
https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html
https://stackoverflow.com/questions/8774593/cmake-link-to-external-library
https://stackoverflow.com/questions/43136418/how-to-add-l-ell-compiler-flag-in-cmake
https://stackoverflow.com/questions/14822794/cmake-to-produce-lpath-llib-link-flags-for-static-libraries

otherwise, appending to a variable like LINK_FLAGS is possible:
https://cmake.org/pipermail/cmake/2014-April/057439.html
https://cmake.org/pipermail/cmake/2017-July/065844.html

the placement of "-lX" matters and can be the reason for ld errors like:
undefined reference to `look_up_our_self'
https://stackoverflow.com/questions/7783345/library-is-linked-but-reference-is-undefined