ITK using ITKPolarTransform with #13 needed:
ITKPolarTransform working with ITK-5.0.1 (< 8c19158422e) but
ITK >= 8c19158422e needed for successful resample tests
ITK using ITKPolarTransform with #13 needed to avoid:

In file included from /opt/itk/include/ITK-5.1/itkPolarToCartesianTransform.h:23:0,
                 from /code/unfold.cxx:7:
/opt/itk/include/ITK-5.1/itkExceptionObject.h:19:2: error: #error "Do not include itkExceptionObject.h directly,  include itkMacro.h instead."
 #error "Do not include itkExceptionObject.h directly,  include itkMacro.h instead."